# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-07 12:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_group_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2017, 6, 7, 22, 0)),
        ),
        migrations.AddField(
            model_name='section',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2017, 6, 7, 22, 0)),
        ),
    ]
