# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-08 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_appuser_grouparticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
