# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-08 01:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_teacher_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('level', models.IntegerField(primary_key=True, serialize=False)),
                ('times', models.IntegerField(default=0)),
                ('students', models.IntegerField(default=0)),
            ],
        ),
    ]
