# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-08 18:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section', to='app.Course'),
        ),
    ]
